on:
  push:
    branches: ["main"]
    paths:
      - 'backend/guideapi/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/guideapi/**'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses : actions/checkout@v3
      - name: Get Java version
        run: |
          Java_Version=$(mvn help:evaluate "-Dexpression=maven.compiler.release" -q -DforceStdout | sed -e 's/^1\./1.0./')
          echo "Java_Version=$Java_Version" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.Java_Version }}
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven
        run: mvn -B compile --file backend/guideapi/pom.xml

      - name: Test with Maven
        run: mvn -B test --file backend/guideapi/pom.xml